channel_sources:
  - robotraconteur,conda-forge
channel_targets:
  - robotraconteur main
macos_min_version:             # [osx]
  - 10.15                      # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.15                      # [osx]
