{% set name = "gazebo_robotraconteur_server_plugin" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/robotraconteur-contrib/RobotRaconteur_Gazebo_Server_Plugin/archive/v{{ version }}.tar.gz
  sha256: a3070be34c9fab1c60502140d5156c47e080779a04cd44015c14c17ea056ac77  

build:
  number: 2


requirements:
  build:
    - git
    - cmake
    - make  # [linux]
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - robotraconteur >=0.18.0
    - robotraconteur_companion >=0.3.1
    - gazebo
    - libboost-devel
    - yaml-cpp
    - eigen
    - pkgconfig
  run:
    - robotraconteur >=0.18.0
    - robotraconteur_companion >=0.3.1
    - {{ pin_compatible('gazebo', max_pin='x.x.x', min_pin='x.x.x') }}
    - yaml-cpp
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

about:
  home: https://github.com/robotraconteur-contrib/RobotRaconteur_Gazebo_Server_Plugin
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Robot Raconteur plugin for the Gazebo Robot Simulator'

extra:
  recipe-maintainers:
    - johnwason
