{% set name = "gazebo_robotraconteur_server_plugin" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/robotraconteur-contrib/RobotRaconteur_Gazebo_Server_Plugin/archive/v{{ version }}.tar.gz
  sha256: a3070be34c9fab1c60502140d5156c47e080779a04cd44015c14c17ea056ac77
  patches:
    - cmake_ver.patch

build:
  number: 5


requirements:
  build:
    - git
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - robotraconteur                         # [build_platform != target_platform]
  host:
    - robotraconteur >=0.18.0
    - robotraconteur_companion >=0.3.1
    - gazebo
    - libboost-devel
    - yaml-cpp
    - eigen
    - pkgconfig
    - libprotobuf
    - libblas
    - tinyxml2
  run:
    - robotraconteur >=0.18.0
    - robotraconteur_companion >=0.3.1
    - {{ pin_compatible('gazebo', max_pin='x.x.x', min_pin='x.x.x') }}
    - yaml-cpp
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    - libprotobuf
    - libboost-devel
    - libblas
    - tinyxml2

about:
  home: https://github.com/robotraconteur-contrib/RobotRaconteur_Gazebo_Server_Plugin
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Robot Raconteur plugin for the Gazebo Robot Simulator'

extra:
  recipe-maintainers:
    - johnwason
